In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
df = pd.read_csv("data.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Columns: 7466 entries, Unnamed: 0 to y
dtypes: int64(7465), object(1)
memory usage: 2.1+ MB


In [5]:
df.describe()

Unnamed: 0       X53416      M83670       X90908       M97496  \
count   36.000000    36.000000   36.000000    36.000000    36.000000   
mean    17.500000   378.750000  177.305556   128.027778   568.305556   
std     10.535654   648.716067  243.494655   787.935802   637.451928   
min      0.000000  -694.000000 -117.000000   -50.000000     8.000000   
25%      8.750000   -95.750000  -31.000000   -13.250000    47.250000   
50%     17.500000   194.500000  117.000000    -4.500000   293.500000   
75%     26.250000   721.750000  330.500000    14.000000  1079.250000   
max     35.000000  1815.000000  718.000000  4723.000000  2261.000000   

          X90908.1       U37019      R48602       T96548      X64559  \
count    36.000000    36.000000   36.000000    36.000000   36.000000   
mean     93.555556   366.833333  140.166667   644.194444   73.444444   
std     557.527370   427.166645  171.443202   685.514231   88.504219   
min     -54.000000    -6.000000  -18.000000    -8.000000   -8.000000   
25%      -7.000000    27.250000   17.750000    33.250000    8.250000   
50%       3.000000   110.500000   37.500000   333.500000   37.500000   
75%      10.250000   675.000000  268.500000  1185.250000  107.750000   
max    3344.000000  1354.000000  718.000000  2203.000000  357.000000   

           T55741       T64171      T54547      M95936      X54162  \
count   36.000000    36.000000   36.000000   36.000000   36.000000   
mean    68.055556    80.000000   64.583333   57.805556   51.388889   
std     90.766244   418.419475   79.530901   73.495897   69.846885   
min    -14.000000   -12.000000  -49.000000  -74.000000  -41.000000   
25%     -0.250000    -0.250000   -3.250000    2.750000    1.750000   
50%     23.500000     5.000000   48.500000   51.500000   21.500000   
75%    109.250000    16.250000  112.500000   98.000000  112.500000   
max    357.000000  2519.000000  230.000000  234.000000  228.000000   

           H57136       M10373      T55200      T46924      L11708  \
count   36.000000    36.000000   36.000000   36.000000   36.000000   
mean    46.888889    44.694444   -0.527778   69.527778   75.611111   
std     67.930543   262.210910  138.904178   85.688301   80.361426   
min    -26.000000   -62.000000 -251.000000  -34.000000  -43.000000   
25%     -8.250000    -7.750000  -74.750000   19.250000   17.750000   
50%     14.500000     4.500000  -27.500000   48.000000   54.500000   
75%     97.250000    12.250000   71.750000   92.500000  115.000000   
max    188.000000  1570.000000  390.000000  380.000000  300.000000   

           M18079      T46933       M98331      H54425       M76378  \
count   36.000000   36.000000    36.000000   36.000000    36.000000   
mean    44.222222   48.083333    42.611111   76.916667   279.916667   
std    116.445232   65.405275   182.716217   86.794132   356.456639   
min     -3.000000  -36.000000     1.000000  -15.000000     8.000000   
25%      8.750000    6.000000     4.000000   19.250000    43.500000   
50%     20.500000   33.500000     8.000000   43.000000   135.000000   
75%     35.250000   73.000000    15.250000  119.000000   285.000000   
max    711.000000  250.000000  1105.000000  351.000000  1336.000000   

           M26393       H59796      M82962       T55255      L13773  \
count   36.000000    36.000000   36.000000    36.000000   36.000000   
mean    40.000000    34.388889   40.694444    37.138889   34.944444   
std     44.593401   213.117845   69.266698   183.331729  121.608727   
min    -19.000000   -25.000000   -6.000000    -3.000000 -647.000000   
25%      0.750000    -9.250000    8.000000     2.750000   27.000000   
50%     32.000000    -0.500000   17.500000     5.000000   43.500000   
75%     73.750000     7.500000   45.750000    11.250000   71.250000   
max    135.000000  1276.000000  394.000000  1106.000000  126.000000   

          X53416.1       M63391      M63603      R33881       M95787  \
count    36.000000    36.000000   36.000000   36.000000    36.000000   
mean    491.972222   54

In [6]:
df['y'] = df['y'].replace("tumor",0)
df['y'] = df['y'].replace("Normal",1)

In [7]:
corr_matrix = df.corr()

In [8]:
corr_matrix['y'].sort_values(ascending=False)

y              1.000000e+00
Unnamed: 0     8.663597e-01
M83670         8.396193e-01
T96548         8.264792e-01
U17077         8.255140e-01
H06524         8.238691e-01
J02854         8.202174e-01
M97496         8.187897e-01
T64297         8.130872e-01
U14631         8.092166e-01
M36634         8.090602e-01
M12272         8.060364e-01
Z49269.1       8.003673e-01
X73502         7.940942e-01
T67077         7.883982e-01
H57136         7.871289e-01
H43887         7.866511e-01
T60155         7.836275e-01
M95787         7.833501e-01
Z49269.2       7.830002e-01
U37019         7.759723e-01
X12496         7.720861e-01
T71025         7.696938e-01
M95936         7.693058e-01
M84526         7.669104e-01
Z31695         7.665767e-01
M63391         7.663961e-01
Z49269         7.648885e-01
T76971         7.642344e-01
R99208         7.638427e-01
M63603         7.636660e-01
M76378.1       7.571250e-01
T51913         7.568935e-01
M76378.2       7.561686e-01
R46753         7.490032e-01
M14745         7.488

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
train_set ,test_set = train_test_split(df, test_size=0.2,random_state=42)

In [11]:
print("Rows in train set: ",len(train_set))
print("Rows in test set: ",len(test_set))

Rows in train set:  28
Rows in test set:  8


In [14]:
df = train_set.drop("y",axis=1)
df_label =train_set["y"].copy()

In [42]:
from sklearn.impute import SimpleImputer

In [43]:
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer.fit(df)

SimpleImputer(strategy='median')

In [44]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline =Pipeline([
    ('imputer', SimpleImputer(strategy ='median')),
    ('std_scaler',StandardScaler())
])

In [45]:
df = my_pipeline.fit_transform(df)

In [62]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
#model =LinearRegression()
#model =DecisionTreeRegressor()
model =RandomForestClassifier()
model.fit(df,df_label)

RandomForestClassifier()

In [63]:
import numpy as np

In [64]:
from sklearn.metrics import mean_squared_error
df_pred = model.predict(df)
lin_mse = mean_squared_error(df_label,df_pred)
lin_rmse = np.sqrt(lin_mse)

In [65]:
lin_mse

0.0

In [66]:
lin_rmse

0.0

In [67]:
from sklearn.model_selection import cross_val_score
scores =cross_val_score(model,df,df_label,scoring='neg_mean_squared_error',cv=10)
rmse = np.sqrt(-scores)

In [68]:
rmse

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.57735027, 0.        , 0.        , 0.        , 0.        ])

In [69]:
def print_scores(scores):
    print("Scores: ", scores)
    print("Mean: ",scores.mean())
    print("Strandard Deviation: ",scores.std())

In [70]:
print_scores(rmse)

Scores:  [0.         0.         0.         0.         0.         0.57735027
 0.         0.         0.         0.        ]
Mean:  0.057735026918962574
Strandard Deviation:  0.17320508075688773


In [71]:
from joblib import dump,load
dump(model,'brain.joblib')

['brain.joblib']

In [72]:
X_test =test_set.drop('y',axis=1)
Y_test =test_set['y'].copy()

In [73]:
X_test_prepared = my_pipeline.transform(X_test)

In [74]:
final_predictions =model.predict(X_test_prepared)
final_mse =mean_squared_error(Y_test,final_predictions)
final_rmse = np.sqrt(final_mse)

In [75]:
final_rmse

0.0

In [76]:
final_mse

0.0

In [77]:
final_predictions

array([1, 0, 1, 1, 0, 1, 1, 0], dtype=int64)

In [78]:
print(final_predictions,list(Y_test))

[1 0 1 1 0 1 1 0] [1, 0, 1, 1, 0, 1, 1, 0]
